<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <form action="/device/store" method="post" accept-charset="utf-8">

            <div class="col-sm-10">
                <div class="form-group <?php echo (isset($this->errors['device'])) ? 'has-error' : ''; ?>">
                    <label for="title">Dispositivo</label>
                    <input type="text" name="device" class="form-control" value="<?php echo (isset($this->inputs['device'])) ? $this->inputs['device'] : ''; ?>" />
                    <?php if (isset($this->errors['device'])) : ?>
                        <span class="help-block"><?php echo $this->errors['device'] ?></span>
                    <?php endif; ?>
                </div>
                <div class="form-group <?php echo (isset($this->errors['address'])) ? 'has-error' : ''; ?>">
                    <label for="title">Endereço ip:</label>
                    <input type="text" name="address" class="form-control" value="<?php echo (isset($this->inputs['address'])) ? $this->inputs['address'] : '';?>" />
                    <?php if (isset($this->errors['address'])) : ?>
                        <span class="help-block"><?php echo $this->errors['address'] ?></span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-xs-12">
                <a href="/products" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</div>