<div class="container">
    <?php $this->renderView('alerts/_success'); ?>
    <?php $this->renderView('alerts/_errors'); ?>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->getPageTitle() ?></h3>
                </div>
                <div class="panel-body">
                    <form action="/user/<?php echo $this->view->user->id ?>/update" method="post" accept-charset="utf-8">
                        <div class="form-group <?php echo (isset($this->errors['name'])) ? 'has-error' : ''; ?>">
                            <label for="title">Nome</label>
                            <input type="text" name="name" class="form-control" value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : $this->view->user->name; ?>" />
                            <?php if (isset($this->errors['name'])) : ?>
                                <span class="help-block"><?php echo $this->errors['name'] ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="form-group <?php echo (isset($this->errors['url'])) ? 'has-error' : ''; ?>">
                            <label for="title">URL do Site</label>
                            <input type="text" name="url" class="form-control" value="<?php echo (isset($this->inputs['url'])) ? $this->inputs['url'] : $this->view->user->url; ?>" />
                            <?php if (isset($this->errors['url'])) : ?>
                                <span class="help-block"><?php echo $this->errors['url'] ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="form-group <?php echo (isset($this->errors['email'])) ? 'has-error' : ''; ?>">
                            <label for="title">Email</label>
                            <input type="email" name="email" class="form-control" value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : $this->view->user->email; ?>" />
                            <?php if (isset($this->errors['email'])) : ?>
                                <span class="help-block"><?php echo $this->errors['email'] ?></span>
                            <?php endif; ?>
                        </div>
                        <div class="form-group <?php echo (isset($this->errors['password'])) ? 'has-error' : ''; ?>">
                            <label for="title">Senha</label>
                            <input type="password" name="password" class="form-control" value="<?php echo (isset($this->inputs['password'])) ? $this->inputs['password'] : ''; ?>" placeholder="Deixe em branco para manter a mesma senha" />
                            <input type="hidden" name="hash" class="form-control" value="<?php echo $this->view->user->password; ?>" />
                            <?php if (isset($this->errors['password'])) : ?>
                                <span class="help-block"><?php echo $this->errors['password'] ?></span>
                            <?php endif; ?>
                        </div>
                        <a href="/users" class="btn btn-default">Cancelar</a>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>