<div class="container">
    <?php $this->renderView('alerts/_success'); ?>
    <?php $this->renderView('alerts/_errors'); ?>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="admin-tab" data-bs-toggle="tab" data-bs-target="#admin" type="button" role="tab" aria-controls="admin" aria-selected="true">Admin</button>
        </li>
        <?php foreach ($this->view->devices as $device) : ?>
            <?php if ($device->user_id == $this->view->user->id) : ?>
                <?php $check = $this->checkCliTarget($device->address); ?>
                <?php if ($check == true) : ?>
                    <?php $this->setCliTarget($device->address, $device->user, $device->password); ?>
                    <?php $this->util->setMenu('/ppp active'); ?>
                    <?php if ($this->util->count() > 0) : ?>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="<?php echo $device->name; ?>-tab" data-bs-toggle="tab" data-bs-target="#<?php echo $device->name; ?>" type="button" role="tab" aria-controls="<?php echo $device->name; ?>" aria-selected="false"><?php echo $device->name; ?></button>
                        </li>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <br />
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="admin" role="tabpanel" aria-labelledby="admin-tab">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <h3 class="h3"><i class="bi-person"></i>Administradores</h3>
                            <p class="card-text text-justify">Usuários com permissões para consultar, alterar e remover informações no sistema</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted float-end">
                                <a class="float-end" href="/user/create">
                                    <button class="btn btn-primary">
                                        <i class="bi-person-plus"></i> Incluir
                                    </button>
                                </a>
                            </small>
                            </p>
                        </div>
                    </div>
                </div>
                <?php foreach ($this->view->users as $user) : ?>
                    <div class="col">
                        <div class="card h-100">
                            <div class="card-body">
                                <a href="/user/<?php echo $user->id; ?>/show">
                                    <h3 class="h3"><i class="bi-person"></i><?php echo $user->name ?></h3>
                                    <p class="card-text text-justify">E-Mail: <?php echo $user->email ?></p>
                                    <p class="card-text text-justify">Site: <?php echo $user->url ?></p>
                                </a>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted float-end">
                                    <a href="/user/<?php echo $user->id ?>/edit">
                                        <button class="btn btn-warning btn-xs" type="button">
                                            <i class="bi-pencil"></i>
                                        </button>
                                    </a>
                                    <a href="/user/<?php echo $user->id ?>/delete">
                                        <button class="btn btn-danger btn-xs" type="button" onclick="return confirm('Deletar esse intem?')">
                                            <i class="bi-trash"></i>
                                        </button>
                                    </a>
                                </small>
                                </p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php foreach ($this->view->devices as $device) : ?>
            <?php if ($device->user_id == $this->view->user->id) : ?>
                <div class="tab-pane fade" id="<?php echo $device->name; ?>" role="tabpanel" aria-labelledby="<?php echo $device->name; ?>-tab">
                    <?php $check = $this->checkCliTarget($device->address); ?>
                    <?php if ($check == true) : ?>
                        <?php $this->setCliTarget($device->address, $device->user, $device->password); ?>
                        <?php $this->util->setMenu('/ppp active'); ?>
                        <?php if ($this->util->count() > 0) : ?>
                            <div class="row row-cols-1 row-cols-md-3 g-4">
                                <?php foreach ($this->util->getAll() as $user) : ?>
                                    <?php  // set name, profile
                                    $name = $user->getProperty('name');
                                    $uptime = $user->getProperty('uptime');
                                    $address = $user->getProperty('address'); ?>
                                    <div class="col">
                                        <div class="card h-100">
                                            <div class="card-body">
                                                <h3 class="h3"><i class="bi-person"></i><?php echo $name; ?></h3>
                                                <p class="card-text text-justify">Tempo de Conexão: <?php echo $uptime; ?>
                                                    <?php //get status for this client
                                                    $this->util->setMenu('/interface');
                                                    $status = $this->util->getAll();
                                                    foreach ($status as $user) {
                                                        if ($user->getProperty('name') == '<pppoe-' . $name . '>') {
                                                            //the next values are prompted in MiB, we will conver to MB and GB to keep user friendly readable || 1 MiB = 1.048576 MB
                                                            $precision = 2;
                                                            $units = array('B', 'KB', 'MB', 'GB', 'TB');
                                                            $rx = max($user->getProperty('rx-byte'), 0);
                                                            $pow = floor(($rx ? log($rx) : 0) / log(1024));
                                                            $pow = min($pow, count($units) - 1);
                                                            $rx /= pow(1024, $pow);
                                                            $rx = round($rx, $precision) . ' ' . $units[$pow];
                                                            $tx = max($user->getProperty('tx-byte'), 0);
                                                            $pow = floor(($tx ? log($tx) : 0) / log(1024));
                                                            $pow = min($pow, count($units) - 1);
                                                            $tx /= pow(1024, $pow);
                                                            $tx = round($tx, $precision) . ' ' . $units[$pow];
                                                        }
                                                    }
                                                    ?>
                                                    <br />Dados recebidos: <?php echo $rx; ?>
                                                    <br />Dados transferidos: <?php echo $tx; ?>
                                                </p>
                                            </div>
                                            <div class="card-footer">
                                                <small class="text-muted float-end">
                                                    <a href="<?php echo 'http://' . $address; ?>" target="_blank">
                                                        <button class="btn btn-primary btn-xs" type="button">
                                                            <i class="bi-router"></i> <?php echo $address; ?>
                                                        </button>
                                                    </a>
                                                </small>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>