<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    <div class="row">
        <div>
            <h1 class="h1 text-center">Backend MPRadMicroframework</h1>
            <p>
                Este é um micro framework MVC em PHP, construído por <a href="mailto:wevertonslima@gmail.com">Weverton S. Lima</a>. Veja mais em nosso site clicando <a href="http://unixlocal.ml/isp">aqui</a>.
            </p>
            <p>
                O intúito é prover um frontend seguro e ágil durante o ciclo de vida da aplicação web(fetch & CRUD) seguindo padrões MVC.
                O sistema foi desenvolvida com recursos já oferecidos em frameworks como Laravel, Illuminate, Symfony, etc;
            </p>
            <p>
                A partir deste painel voce poderá se conectar a seus dispositivos mikrotik e gerenciar seus servidores ppp utilizando-se de database presente em <a href='https://unixlocal.ml/client'>site externo</a>.
            </p>
        </div>
    </div>
</div>