<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
    <div class="row">
        <div>
            <h1 class="h1 text-center">Backend MPRadMicroframework</h1>
            <p>
                Este é um micro framework MVC em PHP, construído por <a href="mailto:wevertonslima@gmail.com">Weverton S. Lima</a>. Veja mais em nosso site clicando <a href="http://unixlocal.ml">aqui</a>.
            </p>
            <p>
                O intúito é prover um frontend seguro e ágil durante o ciclo de vida da aplicação(criação, leitura, atualização, e remoção - CRUD - de dados de usuários e servidores baseados em dados sincronizados do site) web seguindo padrões MVC. Aplicação foi desenvolvida com recursos similares aos oferecidos na internet de frameworks como Laravel, Zend, CakePHP, etc.
            </p>
        </div>
    </div>
</div>