<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <form action="/product/store" method="post" accept-charset="utf-8">

            <div class="col-sm-10">
                <div class="form-group <?php echo($this->errors['product']) ? 'has-error' : ''; ?>">
                    <label for="title">Produto</label>
                    <input type="text" name="product" class="form-control" value="<?php echo (isset($this->inputs['product'])) ? $this->inputs['product'] : '';?>" />
                    <?php if ($this->errors['product']): ?>
                        <span class="help-block"><?php echo $this->errors['product'] ?></span>
                    <?php endif; ?>
                </div>
                <div class="form-group <?php echo($this->errors['description']) ? 'has-error' : ''; ?>">
                    <label for="title">Descrição</label>
                    <textarea type="text" name="description" class="form-control"><?php
                        echo (isset
                                ($this->inputs['description'])) ? $this->inputs['description'] : '';
                        ?></textarea>
                    <?php if ($this->errors['description']): ?>
                        <span class="help-block"><?php echo $this->errors['description'] ?></span>
                    <?php endif; ?>
                </div>
            </div>
            
            <div class="col-sm-2">
                <div class="form-group <?php echo ($this->errors['category_id']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Categories</label>
                    <?php foreach ($this->view->categories as $cat) : ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="category_id[]"
                                       value="<?php echo $cat->id ?>"> <?php echo $cat->name ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="col-xs-12">
                <a href="/products" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</div>