<div class="container">
    <div class="row">
        <h1 class="h1">
            <?php echo $this->getPageTitle(); ?>
            <?php if ($this->auth->check()) : ?>
            <a href="/product/create" class="btn btn-primary pull-right">
                <i class="glyphicon glyphicon-plus-sign"></i> Incluir
            </a>
            <?php endif; ?>
        </h1>
    </div>
    <?php $this->renderView('alerts/_success'); ?>
    <?php $this->renderView('alerts/_errors'); ?>

    <?php foreach ($this->view->products as $product): ?>
        <div class="row">
            <h3 class="h3"><a href="/product/<?php echo $product->id; ?>/show" >
                    <?php echo $product->product; ?></a></h3>
            <p class="text-justify"><?php echo $product->description; ?>
        </div>
        <p>
            <strong>Autor: </strong><?php echo $product->user->name; ?><br/>
            <strong>Categorias: </strong>
            <?php
            foreach ($product->category as $cat) {
                echo $cat->name . " ";
            }
            ?>

            <?php if ($this->auth->check() && $product->user->id == $this->auth->id()) : ?>
            <span class="pull-right">
                <a href="/product/<?php echo $product->id ?>/edit" class="btn-warning btn-xs">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
                <a href="/product/<?php echo $product->id ?>/delete" class="btn-danger btn-xs" onclick="return confirm('Deletar esse intem?')">
                    <i class="glyphicon glyphicon-remove-sign"></i>
                </a>
            </span>
            <?php endif; ?>
        </p>
        <hr />
<?php endforeach; ?>
</div>