<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><i class="bi-router"></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/users">Pessoas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/devices">Dispositivos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">Sobre</a>
                </li>
            </ul>
            <form class="d-flex">
                <?php if ($this->auth->check()) : ?>
                    <span class="navbar-text"><a style="text-decoration: none;" href="/user/<?php echo $this->auth->id();?>/show"><i class="bi-person"> <?php echo $this->auth->name()."&nbsp";?></i></a></span>
                    <a href="/logout"><button class="btn btn-outline-light" type="button"><i class="bi-box-arrow-left"> Logout</i></button></a>
                <?php else : ?>
                    <a href="/login"><button class="btn btn-outline-light" type="button"><i class="bi-box-arrow-in-right"> Login</i></button></a>
                    <a href="/user/create"><button class="btn btn-outline-light" type="button"><i class="bi-pencil"> Register</i></button></a>
                <?php endif; ?>
            </form>
        </div>
    </div>
</nav>